# Project-wide Gradle settings

# Gradle memory
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m

# Enable AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Supported architectures
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Enable Hermes engine
hermesEnabled=true

# Keystore details for release build
MYAPP_UPLOAD_STORE_FILE=my-release-key.keystore
MYAPP_UPLOAD_KEY_ALIAS=my-key-alias
MYAPP_UPLOAD_STORE_PASSWORD=Kondaas2025
MYAPP_UPLOAD_KEY_PASSWORD=Kondaas2025

newArchEnabled=true
