require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-permissions/scripts/setup.rb'  # ← ADD THIS

platform :ios, '16.0'
prepare_react_native_project!

use_modular_headers!

ENV['USE_FRAMEWORKS'] = 'static' unless ENV['USE_FRAMEWORKS']
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'KondaasApp' do
  config = use_native_modules!

  setup_permissions([   # ← ADD THIS BLOCK (only include what you actually use)
    'Camera',
    'Microphone',
    'Notifications',
    'PhotoLibrary',
    'LocationWhenInUse',   # ← ADD THIS
  'LocationAlways',      # ← ADD THIS
  ])

  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseMessaging'
  pod 'FirebaseAppCheck'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,
    :fabric_enabled => false
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end