name: Kondaas Silent Update

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Updated for 2026 standards

      - name: Install Dependencies
        run: npm install

      - name: Push to Revopush
        env:
          REVOPUSH_KEY: ${{ secrets.REVOPUSH_ACCESS_KEY }}
        run: |
          npm install -g @revopush/code-push-cli
          # Using the key directly in the command to avoid login issues
          revopush release-react KondaasApp android -d Production --accessKey $REVOPUSH_KEY
