name: Kondaas Silent Update

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Push to Revopush
        run: |
          npm install -g @revopush/code-push-cli
          # This command uses the secret to "log in" automatically
          revopush release-react KondaasApp android -d Production --accessKey ${{ secrets.REVOPUSH_ACCESS_KEY }}
