name: Kondaas Silent Update

on:
  push:
    branches:
      - kondaas2.0

jobs:
  update:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Check for Secret
        run: |
          if [ -z "${{ secrets.REVOPUSH_ACCESS_KEY }}" ]; then
            echo "ERROR: REVOPUSH_ACCESS_KEY is EMPTY!"
            exit 1
          else
            echo "Secret is found, proceeding..."
          fi

      - name: Install Revopush CLI
        run: yarn global add @revopush/code-push-cli

      - name: CodePush Login
        run: revopush login --access-key ${{ secrets.REVOPUSH_ACCESS_KEY }}

      - name: Push to Revopush
        env:
          MY_ACCESS_KEY: ${{ secrets.REVOPUSH_ACCESS_KEY }}
        run: |
          # Push to Android (allow identical packages)
          revopush release-react "KondaasApp" android -d Production --accessKey $MY_ACCESS_KEY || true

          # Push to iOS (allow identical packages)
          revopush release-react "kondaas-App-iOS" ios -d Production --accessKey $MY_ACCESS_KEY || true